
### demo pattern: "github.com/CoverConnect/ego/tracee.recur"


### add a trace
GET http://localhost:8888/trace?pattern=main.recur HTTP/1.1

### read a function
GET http://localhost:8888/functions HTTP/1.1

### delete a trace
DELETE http://localhost:8888/trace?pattern=main.recur HTTP/1.1
